export const SITE_CONFIG = {
  name: "Bertila",
  legalName: "Bertila Palà Ysamat",
  nif: "46237995Z",
  address: {
    street: "C/ Salvador Morato 6º A",
    city: "Castellví de la Marca",
    province: "Barcelona",
    postalCode: "08732",
    country: "ES",
    region: "Cataluña",
  },
  geo: {
    latitude: 41.3553,
    longitude: 1.6917,
  },
  phone: "+34 610 69 85 23",
  phoneTel: "+34610698523",
  email: "bertypala@gmail.com",
  serviceArea: "Cataluña",
  serviceAreas: ["Barcelona", "Tarragona", "Girona", "Lleida", "Cataluña"],
  priceRange: "Consulta sin compromiso",
  openingHours: "Mo-Fr 09:00-19:00",
  domain: "bertila.es",
  url: "https://bertila.es",
} as const;
